import { Archivo, Berkshire_Swash } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/components/common/ScrollToTop";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const berkshire = Berkshire_Swash({
  variable: "--font-berkshire-mono",
  subsets: ["latin"],
  weight: ["400"],
  display:'swap'
});

export const metadata = {
  title: "Icy Tales",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${berkshire.variable}  antialiased`}
      >
        <ScrollToTop/>
        {children}
        
      </body>
    </html>
  );
}
