/** @format */

import { Archivo, Berkshire_Swash } from "next/font/google";
import "./globals.css";
import { WishlistProvider } from "@/components/context/WishlistContext";
import { AuthProvider } from "@/components/context/AuthContext";
import { CartProvider } from "@/components/context/CartContext";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const berkshire = Berkshire_Swash({
  variable: "--font-berkshire-mono",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata = {
  title: "Icy Tales",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${berkshire.variable}  antialiased`}
      >
        <WishlistProvider>
          <AuthProvider>
            <CartProvider>{children}</CartProvider>
          </AuthProvider>
        </WishlistProvider>
      </body>
    </html>
  );
}
