import { Archivo, Berkshire_Swash } from "next/font/google";
import ScrollToTop from "@/components/common/ScrollToTop";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import { WishlistProvider } from "@/components/context/WishlistContext";



export const metadata = {
  title: "Icy Tales",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`  antialiased`}
      >
        <WishlistProvider>
         <ScrollToTop/>
        {children}
        <Footer/>
        </WishlistProvider>
      
        
      </body>
    </html>
  );
}
